import Head from 'next/head'
import React from 'react'
import Footer from '../Footer'
import Header from './Header'

export default function Layout({ title, children }) {
  return (
    <>
    <Head>
        <title>{ title || 'Find, Order, and learn about us' }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className='flex flex-col justify-between w-full h-screen'>


      <div className='md:w-3/4 mx-auto py-4 sm:-px-4 md:space-x-3'>
        <Header/>
      </div>
      
      <main>
        {children}
      </main>

      <Footer />
    </div>
    </>
  )
}
